### ISSUE TITLE
Maker fails with "x86_64-conda_cos6-linux-gnu-gcc: No such file or directory"

### ISSUE THREAD

**Issue by mbnmbn00** [CompSynBioLab-KoreaUniv/FunGAP#11]
### Problem:
Maker fails with following message:
```
/bin/sh: /home/conda/feedstock_root/build_artifacts/perl_1548813468557/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc: No such file or directory
```

### Reason:
The recent transition to the gcc7 packages of *Conda-forge*.
https://github.com/conda-forge/ruby-feedstock/issues/14

### Solution:
You need to re-install the FunGAP from scratch with `label/cf201901`.
```
conda config --remove channels bioconda
conda config --remove channels conda-forge
conda config --add channels bioconda/label/cf201901
conda config --add channels conda-forge/label/cf201901
conda create -n fungap_1
conda activate test3
```

And follow the installation guide in `INSTALL.md`

**Comment by Kata-Pa** [comment]
Unfortunately this didn't work for me. I get no errors while installing but when I run 
maker -h
I still get this:

Running Mkbootstrap for IndexedBase_14e0 ()
chmod 644 "IndexedBase_14e0.bs"
"/home/katerina87/miniconda3/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- IndexedBase_14e0.bs blib/arch/auto/Bio/DB/IndexedBase_14e0/IndexedBase_14e0.bs 644
"/home/katerina87/miniconda3/bin/perl" "/home/katerina87/miniconda3/lib/5.26.2/ExtUtils/xsubpp"  -typemap "/home/katerina87/miniconda3/lib/5.26.2/ExtUtils/typemap"   IndexedBase_14e0.xs > IndexedBase_14e0.xsc
mv IndexedBase_14e0.xsc IndexedBase_14e0.c
/home/conda/feedstock_root/build_artifacts/perl_1550669032175/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc -c  -I"/home/katerina87/Tools/MAKER/maker-2.31.10/bin" -D_REENTRANT -D_GNU_SOURCE --sysroot=/home/conda/feedstock_root/build_artifacts/perl_1550669032175/_build_env/x86_64-conda_cos6-linux-gnu/sysroot -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -O2   -DVERSION=\"0.00\" -DXS_VERSION=\"0.00\" -fPIC --sysroot=/home/conda/feedstock_root/build_artifacts/perl_1550669032175/_build_env/x86_64-conda_cos6-linux-gnu/sysroot "-I/home/katerina87/miniconda3/lib/5.26.2/x86_64-linux-thread-multi/CORE"   IndexedBase_14e0.c
/bin/sh: 1: /home/conda/feedstock_root/build_artifacts/perl_1550669032175/_build_env/bin/x86_64-conda_cos6-linux-gnu-gcc: not found
Makefile:330: recipe for target 'IndexedBase_14e0.o' failed
make: *** [IndexedBase_14e0.o] Error 127

A problem was encountered while attempting to compile and install your Inline
C code. The command that failed was:
  "make > out.make 2>&1" with error code 2

The build directory was:
/home/katerina87/Tools/MAKER/maker-2.31.10/_Inline/build/Bio/DB/IndexedBase_14e0

To debug the problem, cd to the build directory, and inspect the output files.

Environment PATH = '/home/katerina87/bin:/home/katerina87/.local/bin:/home/katerina87/miniconda3/bin:/home/katerina87/miniconda3/condabin:/home/katerina87/bin:/home/katerina87/.local/bin:/home/katerina87/miniconda3/bin:/home/katerina87/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/bin/usearch:$HOME/.local/bin:~/.cache/:/usr/local/bin/spades/SPAdes-3.11.1-Linux/bin/:/snap/bin:/home/katerina87/bin:/usr/lib/jvm/java-8-openjdk-amd64/bin/java/bin:/home/katerina87/bin:/usr/lib/jvm/java-8-openjdk-amd64/bin/java/bin:/home/katerina87/miniconda3/'
 at /home/katerina87/miniconda3/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 256.
        ...propagated at /home/katerina87/miniconda3/lib/site_perl/5.26.2/Inline/C.pm line 869.
BEGIN failed--compilation aborted at /home/katerina87/miniconda3/lib/site_perl/5.26.2/Bio/DB/IndexedBase.pm line 282.
Compilation failed in require at /home/katerina87/miniconda3/lib/site_perl/5.26.2/base.pm line 100.
        ...propagated at /home/katerina87/miniconda3/lib/site_perl/5.26.2/base.pm line 109.
BEGIN failed--compilation aborted at /home/katerina87/miniconda3/lib/site_perl/5.26.2/Bio/DB/Fasta.pm line 137.
Compilation failed in require at ./bin/maker line 59.
BEGIN failed--compilation aborted at ./bin/maker line 59. 

There is no directory conda in the home folder so I thought that the problem was the same as in https://github.com/ContinuumIO/anaconda-issues/issues/10547 , but maybe not?
