### ISSUE TITLE
Can we use this pipeline for annotation plant genome?

### ISSUE THREAD

**Issue by sunnycqcn** [CompSynBioLab-KoreaUniv/FunGAP#17]
Hello,
The author developed a excellent pipeline for annotation fungal genome. I am working on plant genome. Could I use this pipeline for annotation plant genome?
Thanks,
Fuyou

**Comment by mbnmbn00** [comment]
The reason I named this FunGAP is I only intensely tested with fungal genomes.
If you correctly adjust several options, theoretically it should be okay!!

Here's some guideline (from my paper)

Note 3 - Using FunGAP for nonfungal eukaryotic genomes

Since FunGAP is specialized for fungal genomes, several fungal genome-specific parameters are hard-coded inside the pipeline. This includes --jaccard_clip and --genome_guided_max_intron options in Trinity, --max-intronlen in Hisat, and --fungus flag in Braker and GeneMark. These options are useful for fungal genomes because they have higher gene densities than those of other eukaryotic genomes, and implementing “branch point model” in GeneMark-ET is useful for fungal genomes in gene model training. If they are set improperly, two neighbor genes would be predicted as single big gene. These options can be turned off by passing **--no_braker_fungus**, **--no_jaccard_clip**, and **-- no_genemark_fungus**. In addition, users may set **--max_intron** which is set to 2,000 bp by default for fungal genomes.

Good luck!

**Comment by sunnycqcn** [comment]
thanks，
I will try.
Fuyou 

发自我的 iPhone
