### ISSUE TITLE
"args.maker" should be "args.with_maker"

### ISSUE THREAD

**Issue by robinengler** [CompSynBioLab-KoreaUniv/FunGAP#2]
Hello,
There is a small bug to correct in the "check_dependencies.py" and "fungap.py" files:
"args.maker" should be "args.with_maker"

cheers
Robin

**Comment by robinengler** [comment]
Also the error messages from some of FunGAP's options are not correct.
Here is a patch (also includes the fix for args.maker).


--- fungap.py.orig	2018-06-13 12:13:43.930963464 +0200
+++ fungap.py	2018-06-13 12:02:21.012841436 +0200
@@ -181,7 +181,7 @@
     if args.genome_assembly:
         genome_assembly = os.path.abspath(args.genome_assembly[0])
     else:
-        print '[ERROR] Please provide transcriptome read files'
+        print '[ERROR] Please provide GENOME ASSEMBLY files'
         sys.exit(2)
 
     if args.augustus_species:
@@ -199,7 +199,7 @@
     if args.sister_proteome:
         sister_proteome = os.path.abspath(args.sister_proteome[0])
     else:
-        print '[ERROR] Please provide TRANSCRIPTOME READ FILES'
+        print '[ERROR] Please provide SISTER PROTEOME FILES'
         sys.exit(2)
 
     if args.num_cores:
@@ -219,7 +219,7 @@
         with_trinity = ''
 
     if args.with_maker:
-        with_maker = os.path.abspath(args.maker)
+        with_maker = os.path.abspath(args.with_maker)
     else:
         with_maker = ''

**Comment by mbnmbn00** [comment]
Hi Robin,

Thank you for the kind correction of the code.
I fixed the issues in my internal code as you pointed out, but not released yet because we are preparing a bunch of progress of FunGAP (version 1.0.1) and this needs to be tested. We will release the new version no later than this month. 

Thanks again for your kind corrections!!

All the Best,
Byoungnam Min
