### ISSUE TITLE
How to add functional annotation to protein fasta files genrated by FunGAP

### ISSUE THREAD

**Issue by sajjadasaf** [CompSynBioLab-KoreaUniv/FunGAP#38]
Hello,
I successfully run and completed FunGAP. However at the output folder we have only gff3 and protein fasta files and there is no functional annotation to these protein files. Normally when we do blast with related species then we can get the genes names (hopothetical protein etc). But here we unable to get that. Could you kindly guide me to how to do functional annotation after Fungap completion or there is any why to get results with functional annotation.
The second question is about the interproscan results how can we get interproscan tsv file with families information.
Please help that Fungap can do that functional annoation or we should use final fasta file to use another program.
Thank you

**Comment by mbnmbn00** [comment]
Hi, FunGAP doesn't provide functional annotation although some steps include such jobs to score gene models.

The Following could be considered for functional annotation.
1) Interproscan (Pfam most useful) https://www.ebi.ac.uk/interpro/download/
```
interproscan.sh \
  -i fungap_out_prot.faa \
  -f tsv \
  -appl Pfam,SignalP,TMHMM,SUPERFAMILY \
  --output-file-base <GENOME_NAME> \
  --tempdir tmp \
  --cpu 64
```

2) AntiSMASH (secondary metabolism)  https://antismash.secondarymetabolites.org/#!/download
```
# Generate Genbank file (script is packaged in FunGAP)
$FUNGAP_DIR/generate_genbank.py \
  -f <ASSEMBLY_FILE> \
  -g fungap_out.gff3 \
  -a fungap_out_prot.faa \
  -o fungap_out
~/bin/run_antismash fungap_out.gb . --taxon fungi --cpus 30
# I used Docker version of AntiSMASH
```

3) CAZy (using dbCAN)  http://bcb.unl.edu/dbCAN2/

- I haven't used the tool for a while. So please look at the manual.

Let me know if you have more questions. I usually don't use BLAST because it's hard to decide the good E-value or match_len coverage cutoff.

**Comment by sajjadasaf** [comment]
Dear mbnmbn00,
Thank you very much for your reply. I will try your suggested tools.
