### ISSUE TITLE
RNA-Seq data

### ISSUE THREAD

**Issue by nlapalu** [CompSynBioLab-KoreaUniv/FunGAP#6]
Hi,
Is it possible to use several RNA-seq libs, without merging all reads in one file (to avoid possible chimera during assembly with Trinity ?)
It will be great to deal with fastq.gz files !
Thanks
nico

**Comment by mbnmbn00** [comment]
Unfortunately, FunGAP doesn't support multiple transcriptome samples.
But I believe that using one sample should be enough to make good gene prediction.

FASTQ files are only used in HISAT2, so I think I can adjust HISAT2 operation in FunGAP so that gzipped files can be input in the FunGAP. I will put this on my future features! Thanks for the advice.
