### ISSUE TITLE
about the sofyware

### ISSUE THREAD

**Issue by ld9866** [CompSynBioLab-KoreaUniv/FunGAP#71]
Hello, I see the software you published. Now I want to use it. The species we assembled is a mammal with a genome size of 2.5G. Can I directly use your software to complete the four parts of repeat region, ab initio prediction, homology prediction and annotation merging?

**Comment by mbnmbn00** [comment]
Hello,

The gene predictors used in the FunGAP are eukaryotic gene predictors, so it is possible to use the FunGAP on your mammal genome.

Four options you may consider:
1. `--no_braker_fungus` No --fungus flag in BRAKER for non-fungus genomes
2. `--no_jaccard_clip` No --jaccard_clip flag in Trinity for non-fungus genomes
3. `--no_genemark_fungus` No --fungus flag in GeneMark for non-fungus genomes
4. `--max_intron` Max intron length (Default: 2000 bp)

I wonder if you sequenced RNA for annotation also because FunGAP only works with RNA data.
