### ISSUE TITLE
Is it possible to generate alternative splicing transcripts in final annotation

### ISSUE THREAD

**Issue by chongjing** [CompSynBioLab-KoreaUniv/FunGAP#89]
Hi FunGAP:

After checking many FunGAP annotated genomes, I found there is only one transcript for each gene, and the alternative splicing transcripts are missing. So just curious, is it possible to keep alternative splicing transcripts in the final annotation? Thanks.

Best,
Chongjing

**Comment by mbnmbn00** [comment]
Unfortunately, FunGAP doesn't provide an option to keep alternative splicing in the final annotation. That is partly because it's not well-known that fungi have alternative splicing. Also, including alternative splicing in the GFF could lead to confusion in downstream analysis.

However, there are GFF3 files from Maker, Braker, and Augustus. You could simply integrate them into one file if that's your goal. Note that there could be the exact same gene prediction between the programs, so you may want to remove redundancies.

I can further help you if you describe what you are trying to do.

**Comment by chongjing** [comment]
> 

Thanks for your reply. Indeed, I was trying to annotate a plant genome using FunGAP, following your recommendation in  [https://github.com/CompSynBioLab-KoreaUniv/FunGAP/issues/43](url). I think it would be better to keep alternative splicing transcripts for plant annotation. I'll figure a way from Maker, Braker, and Augustus. Thanks.
