### ISSUE TITLE
Environment issues

### ISSUE THREAD

**Issue by cfz1998** [CompSynBioLab-KoreaUniv/FunGAP#96]
Hi! @mbnmbn00 
The <font color=HotPink>Setup environment</font> in <font color=Blue>INSTALL.md</font> not include <font color=aqua>exonerate, tRNAscan-SE, snoscan. ed.</font>. I think this may bring problems. And the code in <font color=Blue>set_dependencies.py</font> could be updated.

--CF

**Comment by mbnmbn00** [comment]
You are right. When I tested the installation last September, `Maker` and `Busco` couldn't be installed in one environment. That's why I installed `Maker` in a separated environment and just use their binary files.

So if you follow the instruction, `set_dependencies.py` will not cause error.
(Let me know if you need any help here)

But maybe we can install `Maker` and `Busco` in one environment together now.
Ultimately, I would like to drop the `Maker`, and use `exonerate` and `Snap`.
As you mentioned before, `Maker` is too slow.

Thanks for the suggestion.
Right now, I need to finish some urgent work by this summer. So won't have time to do anything big. But I will always try to find time to upgrade this program.

**Comment by cfz1998** [comment]
Thanks！@mbnmbn00
<table><tr><td bgcolor=green>FunGAP</td></tr></table> is a very handy software. Using <table><tr><td bgcolor=green>mpirun</td></tr></table> may be faster.

**Comment by mbnmbn00** [comment]
I'm not very familiar with `miprun`. Hope I can remove Maker in the next major upgrade of FunGAP, and reduce the computing time. I will close this issue for now! Thanks for the valuable suggestion.
